/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:fb27e661-730d-4f09-b627-9af4243fe13f",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_tZ77NcVug",
    "aws_user_pools_web_client_id": "34fl8vj2dkhe6hd7s873u7rca5",
    "oauth": {}
};


export default awsmobile;
